export const myProjects = [
  {
    id: 0,
    name: 'Nutrition Plans',
    slug: 'nutrition-plans',
    image: '/images/projects/nutrition-plans.png',
    github: '',
    live: 'https://www.nutritionplans.co/',
    languages: 'Next.js, Typescript, React.js, Firebase, mdx',
    stack: 'Full Stack',
    description:
      'Nutrition Plans is a Meal Planner Platform where you can choose the plan that you like (Balanced, Vegetarian, Mediterranean, Low Carb, Gluten Free, etc), adapt your diet with your body features, goals and meals settings, and get a personalized diet for your days.',
  },
  {
    id: 0,
    name: 'frichieri.dev',
    slug: 'this-website',
    image: '/images/projects/this-website.png',
    github: '',
    live: 'https://frichieri-dev.vercel.app/',
    languages: 'Next.js, Typescript, React.js, Firebase, mdx & Express',
    stack: 'Front End',
    description:
      'This is my personal website. Under construction, but you can see it in the meantime. I hope you like it.',
  },
  {
    id: 1,
    name: 'almarichnutricion',
    slug: 'almarich-nutricion',
    image: '/images/projects/almarichnutricion.png',
    github: '',
    live: 'https://www.almarichnutricion.com/',
    languages: 'Next.js, Typescript, React.js, Firebase & Express',
    stack: 'Front End',
    description:
      'This is a personal website built for a nutritionist. It has an /admin panel where you can create new blogs with a markdown editor.',
  },
  {
    id: 2,
    name: 'lucasnazardj',
    slug: 'lucasnazardj',
    image: '/images/projects/lucasnazardj.png',
    github: '',
    live: 'https://www.lucasnazar.com/',
    languages: 'Next.js, TypeScript, React, Firebase & CSS.',
    stack: 'Front End',
    description:
      'This is a Dj personal website. It has an /admin panel with auth in order to add and delete next tours.',
  },
  {
    id: 3,
    name: 'pizza-order administator',
    slug: 'pizza-order-administrator',
    image: '/images/projects/pizza-administrator.png',
    github: 'https://github.com/farichieri/pizza-administrator',
    live: 'https://pizza-administrator.vercel.app/',
    languages: 'JavaScript, React, CSS, Node.js, MongoDB, Mongoose & Express',
    stack: 'Full Stack',
    description:
      'Pizza Order Administrator is a web page made for controlling orders and statistics of a pizza shop. The idea si to have multiple users and if the order is set, the kitchen will see the orders panel and change the status of the order to completed when the order is ready. You can test the app with the user: admin and password: 1234 (superAdmin)',
  },
  {
    id: 4,
    name: 'Computechshop',
    slug: 'computechshop',
    image: 'https://frichieri.vercel.app/img/compuTechShop.png',
    github: 'https://github.com/FARichieri/CompuTechShop',
    live: 'https://computechshop.vercel.app/',
    languages:
      'JavaScript, React, Redux, Material-UI, PostgreSQL, Express, Sequelize & Mercadopago',
    stack: 'Full Stack',
    description:
      'An E-commerce of computer products built as the final project of the #soyHenry Full Stack Development Bootcamp. It has an /admin panel with variety of control of stocks and users.',
  },
  {
    id: 5,
    name: 'Comic Book',
    slug: 'comic-booc',
    image: '/images/projects/comicbook.png',
    github: 'https://github.com/farichieri/frichieri-test',
    live: 'https://frichieri-test.vercel.app/',
    languages: 'JavaScript, React, Redux, CSS & Firebase',
    stack: 'Front End',
    description:
      'Comic Book app made as a job test. It consumes data from an API, shows comics and details, has a login and register section, a wishlist, a pagination and a searchbar. Read the README in github to test the live demo.',
  },
  {
    id: 6,
    name: 'Old Personal Website',
    slug: 'old-personal-website',
    image: '/images/projects/old-personal-website.png',
    github: 'https://github.com/farichieri/CV-Portfolio',
    live: 'https://frichieri.vercel.app/',
    languages: 'JavaScript, HTML & CSS',
    stack: 'Front End',
    description: 'My old (1 page static) personal website',
  },
  {
    id: 7,
    name: 'Pokemon PI',
    slug: 'pokemon-pi',
    image: '/images/projects/pokemon.png',
    github: 'https://github.com/FARichieri/PI-Pokemon',
    live: 'https://frichieri-pokemon.vercel.app/',
    languages: 'React.js, JavaScript, PostgreSQL, Sequelize & Express.',
    stack: 'Full Stack',
    description:
      'Individual project for the #soyHenry Full Stack Development Bootcamp. Implementing CRUD operations.',
  },
  {
    id: 8,
    name: 'Marketing Services',
    slug: 'marketing-services',
    image: '/images/projects/marketing-services.png',
    github: 'https://github.com/farichieri/simple-marketing-services',
    live: 'https://marketing-services-test.vercel.app/',
    languages: 'HTML, CSS & JavaScript',
    stack: 'Front End',
    description:
      'Simple website required by a recruitment process. (Not responsive)',
  },
  {
    id: 9,
    name: 'Random Quote Machine',
    slug: 'random-quote-machine',
    image: '/images/projects/random-quote-machine.png',
    github: 'https://github.com/farichieri/Random-Quote-Machine',
    live: 'https://random-quote-machine-xi.vercel.app/',
    languages: 'JavaScript, React, Css',
    stack: 'Front End, freeCodeCamp',
    description:
      'Random Quote Machine made for the freeCodeCamp Front End Development Libraries certification.',
  },
  {
    id: 10,
    name: 'Pomodoro Clock',
    slug: 'pomodoro-clock',
    image: '/images/projects/pomodoro-clock.png',
    github: 'https://github.com/farichieri/pomodoro-clock',
    live: 'https://frichieri-pomodoro-clock.vercel.app/',
    languages: 'JavaScript, React, Css',
    stack: 'Front End, freeCodeCamp',
    description:
      'Pomodoro clock made for the freeCodeCamp Front End Development Libraries certification.',
  },
  {
    id: 12,
    name: 'JavaScript Calculator',
    slug: 'javascript-calculator',
    image: '/images/projects/javascript-calculator.png',
    github: 'https://github.com/farichieri/javascript-calculator',
    live: 'https://frichieri-javascript-calculator.vercel.app/',
    languages: 'JavaScript, React, Css',
    stack: 'Front End, freeCodeCamp',
    description:
      'JavaScript Calculator made for the freeCodeCamp Front End Development Libraries certification.',
  },
  {
    id: 13,
    name: 'Drum Machine',
    slug: 'drum-machine',
    image: '/images/projects/drum-machine.png',
    github: 'https://github.com/farichieri/drum-machine',
    live: 'https://drum-machine-frichieri.vercel.app/',
    languages: 'JavaScript, React, Css',
    stack: 'Front End, freeCodeCamp',
    description:
      'Drum Machine made for the freeCodeCamp Front End Development Libraries certification.',
  },
  {
    id: 14,
    name: 'Markdown Previewer',
    slug: 'markdown-previewer',
    image: '/images/projects/markdown-previewer.png',
    github: 'https://github.com/farichieri/markdown-previewer',
    live: 'https://frichieri-markdown-previewer.vercel.app/',
    languages: 'JavaScript, React, Css',
    stack: 'Front End, freeCodeCamp',
    description:
      'Markdown Previewer made for the freeCodeCamp Front End Development Libraries certification.',
  },
  {
    id: 15,
    name: 'Bar Chart Graph',
    slug: 'bar-chart',
    image: '/images/projects/bar-chart.png',
    github: 'https://github.com/farichieri/data-visualization__bar-chart',
    live: 'https://data-visualization-bar-chart.vercel.app/',
    languages: 'D3.js, JavaScript, HTML & CSS.',
    stack: 'freeCodeCamp, Front End',
    description:
      'Bar Chart Graph project made for the Data Visualization freeCodeCamp certification.',
  },
  {
    id: 16,
    name: 'Scatter Plot Graph',
    slug: 'scatter-plot',
    image: '/images/projects/scatterplot.png',
    github:
      'hhttps://github.com/farichieri/data-visualization__scatterplot-graph',
    live: 'https://data-visualization-scatterplot-graph.vercel.app/',
    languages: 'D3.js, JavaScript, HTML & CSS.',
    stack: 'freeCodeCamp, Front End',
    description:
      'Scatter Plot Graph project made for the Data Visualization freeCodeCamp certification.',
  },
  {
    id: 17,
    name: 'Heat Map Graph',
    slug: 'heat-map',
    image: '/images/projects/heat-map.png',
    github: 'https://github.com/farichieri/data-visualization__heat-map',
    live: 'https://data-visualization-heat-map.vercel.app/',
    languages: 'D3.js, JavaScript, HTML & CSS.',
    stack: 'freeCodeCamp, Front End',
    description:
      'Heat Map Graph project made for the Data Visualization freeCodeCamp certification.',
  },
  {
    id: 18,
    name: 'Tree map Graph',
    slug: 'tree-map',
    image: '/images/projects/tree-map.png',
    github: 'https://github.com/farichieri/data-visualization__treemap-diagram',
    live: 'https://data-visualization-treemap-diagram.vercel.app/',
    languages: 'D3.js, JavaScript, HTML & CSS.',
    stack: 'freeCodeCamp, Front End',
    description:
      'Tree Map Graph project made for the Data Visualization freeCodeCamp certification.',
  },
  {
    id: 19,
    name: 'Choropleth Map Graph',
    slug: 'choropleth-map',
    image: '/images/projects/choropleth-map.png',
    github: 'https://github.com/farichieri/data-visualization__choropleth-map',
    live: 'https://data-visualization-choropleth-map.vercel.app/',
    languages: 'D3.js, JavaScript, HTML & CSS.',
    stack: 'freeCodeCamp, Front End',
    description:
      'Choropleth Map Graph project made for the Data Visualization freeCodeCamp certification.',
  },
  {
    id: 20,
    name: 'Timestamp Microservice',
    slug: 'timestamp-microservice',
    image: '/images/projects/timestamp-microservice.png',
    github: 'https://github.com/farichieri/boilerplate-project-timestamp',
    live: 'https://data-visualization-choropleth-map.vercel.app/',
    languages: 'Node.js & Express.',
    stack: 'freeCodeCamp, Back End',
    description:
      'Timestamp Microservice project made for the Back End Development and APIs freeCodeCamp certification.',
  },
  {
    id: 21,
    name: 'Url Shortener',
    slug: 'timestamp-microservice',
    image: '/images/projects/url-shortener.png',
    github: 'https://github.com/farichieri/boilerplate-project-urlshortener',
    live: 'https://boilerplate-project-urlshortener.farichieri.repl.co/',
    languages: 'Node.js, Express, MongoDB & Mongoose.',
    stack: 'freeCodeCamp, Back End',
    description:
      'Url Shortener project made for the Back End Development and APIs freeCodeCamp certification.',
  },
  {
    id: 22,
    name: 'Header Parser',
    slug: 'header-parser',
    image: '/images/projects/header-parser.png',
    github: 'https://github.com/farichieri/boilerplate-project-headerparser',
    live: 'https://boilerplate-project-headerparser.farichieri.repl.co/',
    languages: 'Node.js & Express.',
    stack: 'freeCodeCamp, Back End',
    description:
      'Header Parser project made for the Back End Development and APIs freeCodeCamp certification.',
  },
  {
    id: 23,
    name: 'Exercise Tracker',
    slug: 'exercise-tracker',
    image: '/images/projects/exercise-tracker.png',
    github: 'https://github.com/farichieri/boilerplate-project-filemetadata',
    live: 'https://boilerplate-project-exercisetracker.farichieri.repl.co/',
    languages: 'Node.js, Express, MongoDB & Mongoose.',
    stack: 'freeCodeCamp, Back End',
    description:
      'Exercise Tracker project made for the Back End Development and APIs freeCodeCamp certification.',
  },
  {
    id: 24,
    name: 'File Metadata',
    slug: 'file-metadata',
    image: '/images/projects/file-metadata.png',
    github: 'https://github.com/farichieri/boilerplate-project-filemetadata',
    live: 'https://boilerplate-project-filemetadata.farichieri.repl.co/',
    languages: 'Node.js, & Express.',
    stack: 'freeCodeCamp, Back End',
    description:
      'File Metadata project made for the Back End Development and APIs freeCodeCamp certification.',
  },
  {
    id: 25,
    name: 'Metric/Imperial Converter',
    slug: 'metric-imperial-converter',
    image: '/images/projects/metric-imperial-converter.png',
    github: 'https://github.com/farichieri/boilerplate-metricimpconverter',
    live: 'https://boilerplate-metricimpconverter.farichieri.repl.co/',
    languages: 'Node.js, Express & Chai',
    stack: 'freeCodeCamp, Back End',
    description:
      'Metric Imperial Converter project made for the Quality Assurance freeCodeCamp certification.',
  },
  {
    id: 26,
    name: 'Issue Tracker',
    slug: 'issue-tracker',
    image: '/images/projects/issue-tracker.png',
    github: 'https://github.com/farichieri/boilerplate-project-issuetracker',
    live: 'https://boilerplate-project-issuetracker.farichieri.repl.co/',
    languages: 'Node.js, Express, MongoDB, mongoose & Chai',
    stack: 'freeCodeCamp, Back End',
    description:
      'Issue Tracker project made for the Quality Assurance freeCodeCamp certification.',
  },
  {
    id: 27,
    name: 'Sudoku Solver',
    slug: 'sudoku-solver',
    image: '/images/projects/sudoku-solver.png',
    github: 'https://github.com/farichieri/boilerplate-project-sudoku-solver',
    live: 'https://boilerplate-project-sudoku-solver.farichieri.repl.co/',
    languages: 'Node.js, Express & Chai',
    stack: 'freeCodeCamp, Back End',
    description:
      'Sudoku Solver project made for the Quality Assurance freeCodeCamp certification.',
  },
  {
    id: 28,
    name: 'American British English Translator',
    slug: 'american-british-english-translator',
    image: '/images/projects/american-british-english-translator.png',
    github:
      'https://github.com/farichieri/boilerplate-project-american-british-english-translator',
    live: 'https://boilerplate-project-american-british-english-translator.farichieri.repl.co',
    languages: 'Node.js, Express & Chai',
    stack: 'freeCodeCamp, Back End',
    description:
      'American British English Translator project made for the Quality Assurance freeCodeCamp certification.',
  },
  {
    id: 29,
    name: 'Stock-checker',
    slug: 'stock-checker',
    image: '/images/projects/stock-checker.png',
    github: 'https://github.com/farichieri/boilerplate-project-stockchecker',
    live: 'https://boilerplate-project-stockchecker.farichieri.repl.co',
    languages: 'Node.js, Express & Chai',
    stack: 'freeCodeCamp, Back End',
    description:
      'Stock checker project made for the Quality Assurance freeCodeCamp certification.',
  },
  {
    id: 30,
    name: 'Anonymous Message Board',
    slug: 'anonymous-message-board',
    image: '/images/projects/anonymous-message-board.png',
    github: 'https://github.com/farichieri/boilerplate-project-messageboard',
    live: 'https://boilerplate-project-messageboard.farichieri.repl.co',
    languages: 'Node.js, Express & Chai',
    stack: 'freeCodeCamp, Back End',
    description:
      'Anonymous Message Board project made for the Quality Assurance freeCodeCamp certification.',
  },
];
