export const myProjects = [
  {
    id: 1,
    name: 'Almarich Nutrición',
    slug: 'almarich-nutricion',
    image: '/images/almarichnutricion.png',
    github: '',
    live: 'https://www.almarichnutricion.com/',
    languages: 'Next.js, Typescript, React.js, Firebase & Express',
    stack: 'All',
    description:
      'Personal website for a nutritionist. It has an /admin panel where you can create new blogs with a markdown editor.',
  },
  {
    id: 2,
    name: 'Marketing Services',
    slug: 'marketing-services',
    image: '/images/marketing-services.png',
    github: 'https://github.com/farichieri/simple-marketing-services',
    live: 'https://marketing-services-test.vercel.app/',
    languages: 'HTML, CSS & JavaScript',
    stack: 'Front End',
    description:
      'Simple website required by a recruitment process. (Not responsive)',
  },
  {
    id: 3,
    name: 'Pokemon PI',
    slug: 'pokemon-pi',
    image: '/images/pokemon.png',
    github: 'https://github.com/FARichieri/PI-Pokemon',
    live: 'https://frichieri-pokemon.vercel.app/',
    languages: 'React.js, JavaScript, PostgreSQL, Sequelize & Express.',
    stack: 'Full Stack',
    description:
      'Individual project for the #soyHenry Full Stack Development Bootcamp. Implementing CRUD operations.',
  },
  {
    id: 4,
    name: 'Computechshop',
    slug: 'computechshop',
    image: 'https://frichieri.vercel.app/img/compuTechShop.png',
    github: 'https://github.com/FARichieri/CompuTechShop',
    live: 'https://computechshop.vercel.app/',
    languages:
      'JavaScript, React, Redux, Material-UI, PostgreSQL, Express, Sequelize & Mercadopago',
    stack: 'Full Stack',
    description:
      'An E-commerce of computer products built as the final project of the #soyHenry Full Stack Development Bootcamp. It has an /admin panel with variety of control of stocks and users.',
  },
  {
    id: 5,
    name: 'Pomodoro Clock',
    slug: 'pomodoro-clock',
    image: '/images/pomodoro-clock.png',
    github: 'https://github.com/farichieri/pomodoro-clock',
    live: 'https://frichieri-pomodoro-clock.vercel.app/',
    languages: 'JavaScript, React, Css',
    stack: 'Front End, freeCodeCamp',
    description:
      'Pomodoro clock made for the freeCodeCamp Front End Development Libraries certification.',
  },
  {
    id: 6,
    name: 'JavaScript Calculator',
    slug: 'javascript-calculator',
    image: '/images/javascript-calculator.png',
    github: 'https://github.com/farichieri/javascript-calculator',
    live: 'https://frichieri-javascript-calculator.vercel.app/',
    languages: 'JavaScript, React, Css',
    stack: 'Front End, freeCodeCamp',
    description:
      'JavaScript Calculator made for the freeCodeCamp Front End Development Libraries certification.',
  },
  {
    id: 7,
    name: 'Drum Machine',
    slug: 'drum-machine',
    image: '/images/drum-machine.png',
    github: 'https://github.com/farichieri/drum-machine',
    live: 'https://drum-machine-frichieri.vercel.app/',
    languages: 'JavaScript, React, Css',
    stack: 'Front End, freeCodeCamp',
    description:
      'Drum Machine made for the freeCodeCamp Front End Development Libraries certification.',
  },
  {
    id: 8,
    name: 'Markdown Previewer',
    slug: 'markdown-previewer',
    image: '/images/markdown-previewer.png',
    github: 'https://github.com/farichieri/markdown-previewer',
    live: 'https://frichieri-markdown-previewer.vercel.app/',
    languages: 'JavaScript, React, Css',
    stack: 'Front End, freeCodeCamp',
    description:
      'Markdown Previewer made for the freeCodeCamp Front End Development Libraries certification.',
  },
  {
    id: 9,
    name: 'Random Quote Machine',
    slug: 'random-quote-machine',
    image: '/images/random-quote-machine.png',
    github: 'https://github.com/farichieri/Random-Quote-Machine',
    live: 'https://random-quote-machine-xi.vercel.app/',
    languages: 'JavaScript, React, Css',
    stack: 'Front End, freeCodeCamp',
    description:
      'Random Quote Machine made for the freeCodeCamp Front End Development Libraries certification.',
  },
  {
    id: 10,
    name: 'Comic Book',
    slug: 'comic-booc',
    image: '/images/comicbook.png',
    github: 'https://github.com/farichieri/frichieri-test',
    live: 'https://frichieri-test.vercel.app/',
    languages: 'JavaScript, React, Redux, CSS & Firebase',
    stack: 'Front End',
    description:
      'Comic Book app made as a job test. It consumes data from an API, shows comics and details, has a login and register section, a wishlist, a pagination and a searchbar. Read the README in github to test the live demo.',
  },
  {
    id: 11,
    name: 'PENDINGS',
    slug: 'pendings',
    image: '/images/asd.png',
    github: 'https://github.com/farichieri/frichieri-test',
    live: 'https://frichieri-test.vercel.app/',
    languages: 'JavaScript, React, Redux, CSS & Firebase',
    stack: 'Front End',
    description:
      'Fix PI and PG backend. Add Booking.com, check pizza-administrator and dev-ter + add rest of freeCodeCamp projects',
  },
  {
    id: 12,
    name: 'Old Personal Website',
    slug: 'old-personal-website',
    image: '/images/old-personal-website.png',
    github: 'https://github.com/farichieri/CV-Portfolio',
    live: 'https://frichieri.vercel.app/',
    languages: 'JavaScript, HTML & CSS',
    stack: 'Front End',
    description: 'My old (1 page static) personal website',
  },
  {
    id: 13,
    name: 'lucasnazardj.com',
    slug: 'lucasnazardj',
    image: '/images/lucasnazardj.png',
    github: '',
    live: 'https://www.lucasnazar.com/',
    languages: 'Next.js, TypeScript, React, Firebase & CSS.',
    stack: 'Front End',
    description:
      'Dj personal website. It has an /admin panel with auth in order to add and delete next tours.',
  },
];
