export const myProjects = [
  {
    id: 1,
    name: 'Almarich Nutrición',
    slug: 'almarich-nutricion',
    image: '/images/almarichnutricion.png',
    github: 'https://github.com/FARichieri/almarichnutricion',
    live: 'https://www.almarichnutricion.com/',
    languages: 'Next.js, Firebase',
  },
  {
    id: 2,
    name: 'Luxury Presence',
    slug: 'luxury-presence',
    image: '/images/luxurypresence.png',
    github: 'https://github.com/FARichieri/luxury-presence-test',
    live: 'https://luxury-presence-test.vercel.app/',
    languages: 'Next.js, Firebase',
  },
  {
    id: 3,
    name: 'Pizza Administrator',
    slug: 'pizza-administrator',
    image: '/images/pokemon.png',
    github: 'https://github.com/FARichieri/PI-Pokemon',
    live: 'https://frichieri-pokemon.vercel.app/',
    languages: 'Next.js, Firebase',
  },
  {
    id: 4,
    name: 'Computechshop',
    slug: 'computechshop',
    image: 'https://frichieri.vercel.app/img/compuTechShop.png',
    github: 'https://github.com/FARichieri/CompuTechShop',
    live: 'https://computechshop.vercel.app/',
    languages: 'Next.js, Firebase',
  },
];
